iblog/blog/urls.py
from django.urls import path

from blog import views
from blog.views import page_not_found

urlpatterns = [
    path('', views.index, name='index'),

    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),

    path('article/<str:category>/', views.article_list, name='article_list'),
    path('article/<str:category>/<int:id>/', views.article_datail, name='article_datail'),
    path('post_comment/<int:post_id>/', views.post_comment, name='post_comment'),

    path('all_articles/', views.all_articles, name='all_articles'),
    path('img/', views.img, name='img'),

    path('search/', views.search, name='search'),
]
handler404 = page_not_found

iblog/ex_blog/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

iblog/iblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from iblog import settings

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),

    path('ueditor/', include('DjangoUeditor.urls')),  # 添加DjangoUeditor的URL

    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

iblog/templates/article_detail.html
{% extends 'base.html' %}
{% block content %}
    <!-- content srart -->
    <div class="am-g am-g-fixed blog-fixed yzq-blog-body">

        <div class="am-u-md-8 am-u-sm-12">
            <div class="am-article-hd">
                <h1 class="am-article-title blog-text-center" style="margin-top: 20px;">{{ article_obj.title }}</h1>

                <div class=" am-article-meta blog-text-center yzq-article-meta">
                    <span class="am-article-bd yzq-article-bd"></span>
                    <span><a href="/article/{{ article_obj.category }}/"
                             class="am-icon-leaf">{{ article_obj.category }}&nbsp;</a></span>
                    <span class="am-icon-user">&nbsp;{{ article_obj.user.author_name }} &nbsp;</span>
                    <span class="am-icon-clock-o">&nbsp;{{ article_obj.created_time }}&nbsp;</span>
                    <span class="am-icon-eye">&nbsp;{{ article_obj.views }}&nbsp;</span>
                    {#                    <span class="am-icon-eye">&nbsp;{{ article_obj.tag }}&nbsp;</span>#}
                    <div id="show_div" style="margin-top: 3px;"></div>
                </div>

                <!-- 内容 -->
                <div class="am-article-bd yzq-article-bd" id="yzq-blog-content">
                    {% autoescape off %}
                        {{ article_obj.body }}
                    {% endautoescape %}
                </div>
                <!-- 上一篇、下一篇-->
                <hr style="background: #290ed0;border: none;height: 1px;margin-bottom: 0;">
                <hr id="comment">
                {% if previous_obj %}
                    上一篇：
                    <a href="/article/{{ previous_obj.category }}/{{ previous_obj.id }}/"
                       title="{{ previous_obj.title }}"
                       onclick="MtaH5.clickStat('25')">
                        {{ previous_obj.title }}
                    </a>
                {% endif %}


                <br>
                {% if next_obj %}
                    下一篇：
                    <a href="/article/{{ next_obj.category }}/{{ next_obj.id }}/" title="{{ next_obj.title }}"
                       onclick="MtaH5.clickStat('25')">
                        {{ next_obj.title }}
                    </a>
                {% endif %}


                <hr>

                <!-- 评论-->
                <hr style="background: #6ad013;border: none;height: 1px;margin-bottom: 0;">
                <div id="comment">
                    {% csrf_token %}
                    <div class="am-form-group am-input-group-danger">
                       <textarea cols="102" rows="5" id="comment-content"
                                 contenteditable="true" placeholder='&nbsp;* 想说点什么 ◠‿◠'
                                 name="body"></textarea>
                    </div>
                    <p>
                        <button class="btn btn-primary btn-block" tabindex="4" onclick="get_comment_content()">发表评论
                        </button>
                    </p>

                </div>

                <div class="comment">
                    <ul class="am-comments-list am-comments-list-flip">
                        {% for blog_com in blogcomment_obj %}
                            <article class="am-comment">
                                <img src="https://sdn.geekzu.org/avatar/57e78de5c6e06e185720747d021e72ff.jpg?s=48&amp;d=wavatar&amp;r=g"
                                     alt="大侠" class="am-comment-avatar" width="48" height="48"
                                     onerror="this.src='http://sdn.geekzu.org/avatar/default'">

                                <div class="am-comment-main">
                                    <header class="am-comment-hd">
                                        <div class="am-comment-meta">{{ blog_com.created_time }}</div>
                                    </header>
                                    <div class="am-comment-bd">
                                        {{ blog_com }}
                                    </div>
                                </div>
                            </article>
                            <br>
                        {% endfor %}

                    </ul>
                </div>

            </div>

        </div>
        <!-- content end -->
        <div class="am-u-md-4 am-u-sm-12 blog-sidebar" id="ad">

            <!--个人信息-->
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>About Author</span></h2>
                <div class="am-img-circle">
                    <img src="/static/images/icon/my.jpg" alt="about me" class="round_icon">
                </div>
                <p><b>zxy</b> ( 中原·丐帮 )</p>
                <p>远赴人间惊鸿宴，一睹人间盛世颜。</p>
                <br>
                <p>我是
                    xy（向阳），应届本科毕业生，想找个工作
                    😊</p>
            </div>

            <!--gitee链接-->
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>Contact Author</span></h2>
                <p>
                    <a href="mailto:1943374299@qq.com" title="发邮件给我"><span
                            class="am-icon-envelope am-icon-fw blog-icon"></span></a>

                    <a target="_blank" href="https://gitee.com/xiangyang929/" title="my github"><span
                            class="am-icon-github am-icon-fw blog-icon"></span></a>
                    <a target="_blank" href="https://gitee.com/xiangyang929/" title="我的码云"><span
                            class="am-icon-cloud am-icon-fw blog-icon"></span></a>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1943374299&amp;site=qq&amp;menu=yes"
                       title="QQ 联系我"><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>


                </p>
            </div>
            <!--兼职-->
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>我有一个朋友</span></h2>
                <p>专门帮别人</p>
                <p>写毕业设计程序系统</p>
                <p>网站管理系统搭建</p>
                <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1943374299&amp;site=qq&amp;menu=yes"
                   title="QQ 联系我"><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>
            </div>


        </div>
    </div>

    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>


    <script type="text/javascript">
        function get_comment_content() {
            // jQuery 获取文本输入的内容
            var comment_content = $('#comment-content').val();
            {#var comment_content = $('#comment-content').text();#}
            params = {'comment_content': comment_content, csrfmiddlewaretoken: '{{ csrf_token }}'}
            $.post('/post_comment/{{ article_obj.id }}/', params, function (data) {
                if (data.res == 1) {
                    alert('评论成功')
                    window.location.reload()  //刷新页面
                } else {
                    alert(data.res)
                }

            })
        }

    </script>
{% endblock %}

iblog/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱博客 | 爱上博客 | www.ibllog.cool</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link rel="icon" type="image/png" href="/static/assets/i/favicon.jpgg">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="/static/assets/i/favicon.jpg">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="apple-touch-icon-precomposed" href="/static/assets/i/favicon.jpg">
    <meta name="msapplication-TileColor" content="#0e90d2">
    <link rel="stylesheet" href="/static/assets/css/amazeui.min.css">
    <link rel="stylesheet" href="/static/assets/css/app.css">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

</head>

<body id="blog">
<hr>
<nav class="am-g am-g-fixed blog-fixed blog-nav">
    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button"
            data-am-collapse="{target: '#blog-collapse'}"><span class="am-sr-only">导航切换</span> <span
            class="am-icon-bars">博客导航</span></button>

    <div class="am-collapse am-topbar-collapse" id="blog-collapse">
        <ul class="am-nav am-nav-pills am-topbar-nav">
            <li class="{{ index_active }}"><a href="/"><span class="am-icon-home">&nbsp;首页</span></a></li>

            <li class="am-dropdown" data-am-dropdown>
                <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                    <span class="am-icon-leaf" style="{{ category_active }}">&nbsp; {{ category_name }}</span> <span
                        class="am-icon-caret-down" style="{{ category_active }}"></span>
                </a>
                <ul class="am-dropdown-content">
                    {% for category in category_list %}
                        <a href="/article/{{ category }}/">
                            <li class="am-active">{{ category.name }} ({{ category.num_arts }})</li>
                        </a>
                    {% endfor %}
                </ul>
            </li>

            <li class="{{ is_active }}"><a href="{% url 'blog:all_articles' %}">
                <span class="am-icon-archive" style="{{ all_articles_active }}"> 标准文章</span></a>
            </li>
            <li class="{{ is_active }}"><a href="{% url 'blog:img' %}">
                <span class="am-icon-photo" style="{{ all_imgs_active }}"> &nbsp;图片库</span></a>
            </li>
            <li class="{{ is_active }}"><a href="#"><span class="am-icon-link">友链</span></a></li>

        </ul>

        <form class="am-topbar-form am-topbar-right am-form-inline" role="search" method="get"
              action="/search/">
            <div class="am-form-group">
                <input type="text" class="am-form-field am-input-sm" name="search" placeholder="搜索文章标题" required>
            </div>
        </form>

        <div class="am-collapse am-topbar-collapse" id="blog-collapse">
            <ul class="am-topbar-form am-topbar-right am-form-inline">
                <div class="am-nav am-nav-pills am-topbar-nav">

                    {% if user.is_authenticated %}
                        <span>{{ user.username }}</span>
                        <a href="{% url 'blog:logout' %}">
                            <span>Logout</span></a>
                        {% else %}
                        <a href="{% url 'blog:user_login' %}">
                            <span>Login</span></a>
                    {% endif %}

                </div>


            </ul>
        </div>


    </div>
</nav>
<hr style="background: #290ed0;border: none;height: 1px;margin-bottom: 0;">

{% block content %}
    <!-- 内容-->
    　{% endblock %}

<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>
{#<button type="button" id="BackTop" class="am-gotop-icon am-icon-chevron-up" style="z-index: 100;"></button>#}

<footer class="blog-footer">
    <div class="am-g am-g-fixed blog-fixed am-u-sm-centered blog-footer-padding">
        <div class="am-u-sm-12 am-u-md-4- am-u-lg-4">
            <h3>模板简介</h3>
            <p class="am-text-sm">这是一个使用amazeUI做的简单的前端模板。
                <br> 博客/ 资讯类 前端模板
                <br> 支持响应式，多种布局，包括主页、文章页、媒体页、分类页等
                <br>我是站在了巨人的肩膀上。加油<br><br>
            </p>
        </div>
        <div class="am-u-sm-12 am-u-md-4- am-u-lg-4">
            <h3>社交账号</h3>
            <p>
                <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=1943374299&amp;site=qq&amp;menu=yes" title="QQ"><span
                        class="am-icon-qq am-icon-fw am-primary blog-icon blog-icon"></span></a>
                <a href="https://gitee.com/xiangyang929/" title="my github"><span
                        class="am-icon-github am-icon-fw blog-icon blog-icon"></span></a>
                <a href="https://gitee.com/xiangyang929/" title="我的码云"><span
                        class="am-icon-cloud am-icon-fw blog-icon "></span></a>
                <a href="mailto:1943374299@qq.com" title="发邮件给我"><span
                        class="am-icon-envelope am-icon-fw blog-icon"></span></a>
            </p>
            <h3>小猪给我说</h3>
            <p>生活不易，我们好好努力！</p>
        </div>
        <div class="am-u-sm-12 am-u-md-4- am-u-lg-4">
            <h3>常用网站</h3>
            <p>
            <ul>

                <li class="am-text-sm">
                    <a href="https://docs.python.org/zh-cn/3/" target="_blank"
                       onclick="MtaH5.clickStat('15',{'2':'https://docs.python.org/zh-cn/3/'})">
                        python 3 中文文档
                    </a>
                </li>

                <li class="am-text-sm">
                    <a href="https://docs.djangoproject.com/en/2.2/" target="_blank"
                       onclick="MtaH5.clickStat('15',{'2':'https://docs.djangoproject.com/en/2.2/'})">
                        Django 2.2 英文文档
                    </a>
                </li>


                <li class="am-text-sm">
                    <a href="https://www.yangqq.com/download/div/" target="_blank"
                       onclick="MtaH5.clickStat('15',{'2':'https://www.yangqq.com/download/div/'})">
                        个人网站模板
                    </a>
                </li>


                <li class="am-text-sm">
                    <a href="https://www.bootcdn.cn/" target="_blank"
                       onclick="MtaH5.clickStat('15',{'2':'https://www.bootcdn.cn/'})">
                        BootCDN
                    </a>
                </li>

                <li class="am-text-sm">
                    <a href="https://v3.bootcss.com/" target="_blank"
                       onclick="MtaH5.clickStat('15',{'2':'https://v3.bootcss.com/'})">
                        Bootstrap
                    </a>
                </li>

                <li class="am-text-sm">
                    <a href="https://cn.vuejs.org/" target="_blank"
                       onclick="MtaH5.clickStat('15',{'2':'https://cn.vuejs.org/'})">
                        Vue
                    </a>
                </li>

            </ul>
            </p>
        </div>
    </div>
    <div class="blog-text-center">© Copyright &copy; zxy 2020
        <br>
        备案号：<a href="http://www.beian.miit.gov.cn/" target="_blank">豫ICP备20007445号-1</a>
    </div>


    <div class="blog-text-center">
        <script type="text/javascript">document.write(unescape("%3Cspan id='cnzz_stat_icon_1279044893'%3E%3C/span%3E%3Cscript " +
            "src='https://v1.cnzz.com/z_stat.php%3Fid%3D1279044893%26online%3D1%26show%3Dline' " +
            "type='text/javascript'%3E%3C/script%3E"));</script>
    </div>

</footer>
<!-- banner end -->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/static/assets/js/jquery.min.js"></script>
<!--<![endif]-->
<!--[if lte IE 8 ]>
<script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->
<script src="/static/assets/js/amazeui.min.js"></script>
<script src="/static/assets/js/pinto.min.js"></script>
<script src="/static/assets/js/img.js"></script>
<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 26px;
        height: 7px;
        border-radius: 2px;
        background: orange;
        position: absolute;
        content: "";

    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.0rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.0rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>
</body>
</html>

iblog/templates/img.html
{% extends 'base.html' %}
{% block content %}
    <!-- content srart -->
    <div class="am-g am-g-fixed blog-fixed blog-content">
        <figure data-am-widget="figure" class="am am-figure am-figure-default " data-am-figure="{  pureview: 'true' }">
            <div id="container">
                <div><img src="/static/images/01.jpg">
                    <h3>Agfa</h3></div>
                <div><img src="/static/images/02.jpg">
                    <h3>Auto</h3></div>
                <div><img src="/static/images/03.jpg">
                    <h3>Bald eagle</h3></div>
                <div><img src="/static/images/04.jpg">
                    <h3>Black swan</h3></div>
                <div><img src="/static/images/05.jpg">
                    <h3>Book shelf</h3></div>
                <div><img src="/static/images/06.jpg">
                    <h3>Camera</h3></div>
                <div><img src="/static/images/07.jpg">
                    <h3>Camera</h3></div>
                <div><img src="/static/images/25.jpg">
                    <h3>Vintage camera</h3></div>
                <div><img src="/static/images/09.jpg">
                    <h3>Coffee</h3></div>
                <div><img src="/static/images/10.jpg">
                    <h3>Cookies</h3></div>
                <div><img src="/static/images/11.jpg">
                    <h3>Cubes</h3></div>
                <div><img src="/static/images/12.jpg">
                    <h3>DJ</h3></div>
                <div><img src="/static/images/13.jpg">
                    <h3>Doors</h3></div>
                <div><img src="/static/images/14.jpg">
                    <h3>Matchbox</h3></div>
                <div><img src="/static/images/15.jpg">
                    <h3>Freiburg</h3></div>
                <div><img src="/static/images/16.jpg">
                    <h3>Henna</h3></div>
                <div><img src="/static/images/17.jpg">
                    <h3>Home office</h3></div>
                <div><img src="/static/images/18.jpg">
                    <h3>iPad</h3></div>
                <div><img src="/static/images/19.jpg">
                    <h3>Keyboard</h3></div>
            </div>
        </figure>
    </div>
{% endblock %}

iblog/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <!-- banner start -->
    <div class="am-g am-g-fixed blog-fixed am-u-sm-centered blog-article-margin">
        <div data-am-widget="slider" class="am-slider am-slider-b1" data-am-slider='{&quot;controlNav&quot;:false}'>
            <ul class="am-slides">
                <li>
                    <img src="/static/assets/i/f12.jpg">
                </li>
                <li>
                    <img src="/static/assets/i/f10.jpg">
                </li>
                <li>
                    <img src="/static/assets/i/f19.jpg">
                </li>
                <li>
                    <img src="/static/assets/i/f22.jpg">
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

iblog/templates/list.html
{% extends 'base.html' %}
{% block content %}
    <!-- content srart -->
    <div class="am-g am-g-fixed blog-fixed yzq-blog-body">
        <div class="am-u-md-8 am-u-sm-12">
            <article class="am-g blog-entry-article">
                <div class=" am-u-lg-12 am-u-md-12 am-u-sm-12 blog-entry-text am-text-left">

                    {% autoescape off %}
                        {% for article in page_object %}
                            <hr>
                            <h1><a href="/article/{{ article.category }}/{{ article.id }}/">{{ article.title }}</a></h1>
                            <a href="/article/{{ article.category }}/{{ article.id }}/">
                                {{ article.body|truncatechars_html:150 }}<h5>......点击查看全部</h5></a>
                            <a href="/article/{{ article.category }}/{{ article.id }}/" class="am-article-meta"
                               style="font-size: 1.5rem">
                            </a>
                            <p class="am-article-meta"><a href="" class="blog-continue">continue reading</a>
                                <span><a href="/article/{{ article.category }}/"
                                         class="am-icon-leaf"> {{ article.category }} &nbsp;</a></span>
                                <span class="am-icon-user"> {{ article.user.author_name }} &nbsp;</span>
                                <span class="am-icon-clock-o">&nbsp;{{ article.created_time }}&nbsp;</span>
                                <span class="am-icon-eye">&nbsp;{{ article.views }}&nbsp;</span>
                            </p>
                        {% endfor %}
                    {% endautoescape %}
                </div>
            </article>

        </div>
        <!--  分页 -->
        <div class="am-g am-g-fixed blog-fixed yzq-blog-body">
            <div class="am-u-md-8 am-u-sm-12">
                <ul data-am-widget="pagination" class="am-pagination am-pagination-select am-no-layout">
                    {% if page_object.has_previous %}
                        <li class="am-pagination-prev"><a
                                href="?page={{ page_object.previous_page_number }}">上一页</a></li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1"><i
                                    class="ion ion-chevron-left"></i></a>
                        </li>
                    {% endif %}

                    <li class="am-pagination-select"><a>{{ page_object.number }}/{{ paginator.num_pages }}</a></li>

                    {% if page_object.has_next %}
                        <li class="am-pagination-next"><a href="?page={{ page_object.next_page_number }}">下一页</a>
                            {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1"><i
                                    class="ion ion-chevron-left"></i></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

iblog/templates/login.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱博客 | 爱上博客 | www.ibllog.cool</title>

    <!-- Set render engine for 360 browser -->
    <meta name="renderer" content="webkit">

    <!-- No Baidu Siteapp-->
    <meta http-equiv="Cache-Control" content="no-siteapp"/>

    <link rel="icon" type="image/png" href="/static/assets/i/favicon.jpg">

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="/static/assets/i/favicon.jpg">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="apple-touch-icon-precomposed" href="/static/assets/i/favicon.jpg">

    <meta name="msapplication-TileImage" content="/static/assets/i/favicon.jpg">
    <meta name="msapplication-TileColor" content="#0e90d2">


    <link rel="stylesheet" href="/static/assets/css/amazeui.min.css">
    <link rel="stylesheet" href="/static/assets/css/app.css">
</head>
<body>
<header>
    <div class="log-header">
        <h1><a href="/">爱博客</a></h1>
    </div>
    <div class="log-re">
        <button type="button" class="am-btn am-btn-default am-radius log-button"
                onclick="window.location.href='/register/'">注册
        </button>
    </div>
</header>

<div class="log">
    <div class="am-g">
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-8 am-u-sm-centered log-content">
            <h1 class="log-title am-animation-slide-top">爱博客 www.iblog.cool</h1>
            <br>
            <form class="am-form" id="log-form" method="post" action="/login/">
                {% csrf_token %}
                <div class="am-input-group am-radius am-animation-slide-left">
                    <input type="email" id="doc-vld-email-2-1" class="am-radius" data-validation-message="请输入正确邮箱地址"
                           name="email" placeholder="邮箱" required/>
                    <span class="am-input-group-label log-icon am-radius"><i
                            class="am-icon-user am-icon-sm am-icon-fw"></i></span>
                </div>
                <br>
                <div class="am-input-group am-animation-slide-left log-animation-delay">
                    <input type="password" class="am-form-field am-radius log-input"
                           name="password" placeholder="密码" minlength="6"
                           required>
                    <span class="am-input-group-label log-icon am-radius"><i
                            class="am-icon-lock am-icon-sm am-icon-fw"></i></span>
                </div>
                <br>
                <button type="submit"
                        class="am-btn am-btn-primary am-btn-block am-btn-lg am-radius am-animation-slide-bottom log-animation-delay">
                    登 录
                </button>
                {{ msg }}
                <p class="am-animation-slide-bottom log-animation-delay"><a href="#">忘记密码?</a></p>

                <div class="am-btn-group  am-animation-slide-bottom log-animation-delay-b">
                    <p>使用第三方登录</p>
                    <a href="/accounts/github/login/?process=login"
                       class="am-btn am-btn-secondary am-btn-sm">
                        <i class="am-icon-github am-icon-sm"></i>Github</a>

                    <a href="/accounts/baidu/login/?process=login"
                       class="am-btn am-btn-secondary am-btn-sm">
                        <i class="am-icon-github am-icon-sm"></i>Baidu</a>

                </div>
            </form>
        </div>
    </div>

</div>


<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/static/assets/js/jquery.min.js"></script>
<!--<![endif]-->
<!--[if lte IE 8 ]>
<script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="/static/assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->
<script src="/static/assets/js/amazeui.min.js"></script>
<script src="/static/assets/js/app.js"></script>
</body>
</html>